name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Docker Build
      run: docker build . --file Dockerfile --tag zubayrrr/guestbook-go:$(date +%s)
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/guestbook-go
