name: Docker Image CI

on:
  pull_request_review:
    types:
      - submitted

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE') || github.event.pull_request.merged == true
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/guestbook-go:latest
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/guestbook-go
