name: Docker Image CI

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-n-push:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/guestbook-go:latest
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/guestbook-go
