name: Docker Image CI

on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test out our github action with no image version
    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: test 
      id: test
      uses: ryanjfrizzell/action-bpd@master
      with:
        docker_registry_url: 'hub.docker.com'
        docker_registry_owner: 'zubayrrr'
        docker_repository: 'action-bpd'
        docker_image: 'bpdautolatest'
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
        dockerfile: 'Dockerfile'
    - name: Get the output
      run: |
          echo "imageinfo was ${{ steps.test.outputs.imageinfo }}"
